/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _authSignupSplatRouteImport } from './routes/__auth/signup.$'
import { Route as _authLoginSplatRouteImport } from './routes/__auth/login.$'

const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _authSignupSplatRoute = _authSignupSplatRouteImport.update({
  id: '/__auth/signup/$',
  path: '/signup/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _authLoginSplatRoute = _authLoginSplatRouteImport.update({
  id: '/__auth/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/decks': typeof DecksRoute
  '/pools': typeof PoolsRoute
  '/login/$': typeof _authLoginSplatRoute
  '/signup/$': typeof _authSignupSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/decks': typeof DecksRoute
  '/pools': typeof PoolsRoute
  '/login/$': typeof _authLoginSplatRoute
  '/signup/$': typeof _authSignupSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cards': typeof CardsRoute
  '/decks': typeof DecksRoute
  '/pools': typeof PoolsRoute
  '/__auth/login/$': typeof _authLoginSplatRoute
  '/__auth/signup/$': typeof _authSignupSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cards'
    | '/decks'
    | '/pools'
    | '/login/$'
    | '/signup/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/cards' | '/decks' | '/pools' | '/login/$' | '/signup/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cards'
    | '/decks'
    | '/pools'
    | '/__auth/login/$'
    | '/__auth/signup/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardsRoute: typeof CardsRoute
  DecksRoute: typeof DecksRoute
  PoolsRoute: typeof PoolsRoute
  _authLoginSplatRoute: typeof _authLoginSplatRoute
  _authSignupSplatRoute: typeof _authSignupSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/signup/$': {
      id: '/__auth/signup/$'
      path: '/signup/$'
      fullPath: '/signup/$'
      preLoaderRoute: typeof _authSignupSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/login/$': {
      id: '/__auth/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof _authLoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardsRoute: CardsRoute,
  DecksRoute: DecksRoute,
  PoolsRoute: PoolsRoute,
  _authLoginSplatRoute: _authLoginSplatRoute,
  _authSignupSplatRoute: _authSignupSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
